name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码到工作目录

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # 配置 Java 环境
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon  # 使用 Gradle 构建项目

      - name: Build with Gradle
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          files: "build/libs/"
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: true